# Generated by Django 5.2.5 on 2025-08-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('age', models.PositiveIntegerField(verbose_name='年齢')),
                ('position', models.CharField(choices=[('GK', 'ゴールキーパー'), ('DF', 'ディフェンダー'), ('MF', 'ミッドフィールダー'), ('FW', 'フォワード')], max_length=2, verbose_name='ポジション')),
                ('jersey_number', models.PositiveIntegerField(unique=True, verbose_name='背番号')),
            ],
            options={
                'ordering': ['jersey_number'],
            },
        ),
    ]
