# Generated by Django 5.2.5 on 2025-08-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('GK', 'ゴールキーパー'), ('LSB', 'レフトサイドバック'), ('CB', 'センターバック'), ('RSB', 'ライトサイドバック'), ('DMF', 'ディフェンシブミッドフィールダー'), ('LMF', 'レフトミッドフィールダー'), ('CMF', 'センターミッドフィールダー'), ('RMF', 'ライトミッドフィールダー'), ('OMF', 'オフェンシブミッドフィールダー'), ('FW', 'フォワード')], max_length=3, verbose_name='ポジション'),
        ),
    ]
